# Generated by Django 5.1.5 on 2025-02-02 10:42

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_room_image_alter_room_price_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=reservations.models.room_images),
        ),
    ]
