# Generated by Django 5.1.5 on 2025-02-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_room_image_room_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='gambar',
        ),
        migrations.AddField(
            model_name='room',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
